// Code generated by protoc-gen-go.
// source: sale.proto
// DO NOT EDIT!

package igrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// {订单号，布匹颜色数量单位列表信息={颜色信息，面料信息，数量，单位:米/匹, 总重量}, 仓管员, 仓库地点, 收货地点, 订单总金额, 更新时间}
type SaleOrder struct {
	SaleOrderId     int64 `protobuf:"varint,1,opt,name=SaleOrderId" json:"SaleOrderId,omitempty"`
	SaleOrderItemId int64 `protobuf:"varint,2,opt,name=SaleOrderItemId" json:"SaleOrderItemId,omitempty"`
}

func (m *SaleOrder) Reset()                    { *m = SaleOrder{} }
func (m *SaleOrder) String() string            { return proto.CompactTextString(m) }
func (*SaleOrder) ProtoMessage()               {}
func (*SaleOrder) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *SaleOrder) GetSaleOrderId() int64 {
	if m != nil {
		return m.SaleOrderId
	}
	return 0
}

func (m *SaleOrder) GetSaleOrderItemId() int64 {
	if m != nil {
		return m.SaleOrderItemId
	}
	return 0
}

type WarehouseManagerMessage struct {
	Name                      string                      `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Id                        int64                       `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
	ColorPatternRelationships []*ColorPatternRelationship `protobuf:"bytes,3,rep,name=ColorPatternRelationships" json:"ColorPatternRelationships,omitempty"`
	SaleOrderNo               string                      `protobuf:"bytes,4,opt,name=SaleOrderNo" json:"SaleOrderNo,omitempty"`
}

func (m *WarehouseManagerMessage) Reset()                    { *m = WarehouseManagerMessage{} }
func (m *WarehouseManagerMessage) String() string            { return proto.CompactTextString(m) }
func (*WarehouseManagerMessage) ProtoMessage()               {}
func (*WarehouseManagerMessage) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *WarehouseManagerMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WarehouseManagerMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WarehouseManagerMessage) GetColorPatternRelationships() []*ColorPatternRelationship {
	if m != nil {
		return m.ColorPatternRelationships
	}
	return nil
}

func (m *WarehouseManagerMessage) GetSaleOrderNo() string {
	if m != nil {
		return m.SaleOrderNo
	}
	return ""
}

type WarehouseManagers struct {
	WarehouseManagerMessages []*WarehouseManagerMessage `protobuf:"bytes,1,rep,name=WarehouseManagerMessages" json:"WarehouseManagerMessages,omitempty"`
}

func (m *WarehouseManagers) Reset()                    { *m = WarehouseManagers{} }
func (m *WarehouseManagers) String() string            { return proto.CompactTextString(m) }
func (*WarehouseManagers) ProtoMessage()               {}
func (*WarehouseManagers) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *WarehouseManagers) GetWarehouseManagerMessages() []*WarehouseManagerMessage {
	if m != nil {
		return m.WarehouseManagerMessages
	}
	return nil
}

type ShopMessage struct {
	SaleOrderNo               string                      `protobuf:"bytes,1,opt,name=SaleOrderNo" json:"SaleOrderNo,omitempty"`
	Id                        int64                       `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
	ColorPatternRelationships []*ColorPatternRelationship `protobuf:"bytes,3,rep,name=ColorPatternRelationships" json:"ColorPatternRelationships,omitempty"`
	DeliveriedAtPlaceName     string                      `protobuf:"bytes,4,opt,name=DeliveriedAtPlaceName" json:"DeliveriedAtPlaceName,omitempty"`
	OutbundedAtPlaceName      string                      `protobuf:"bytes,5,opt,name=OutbundedAtPlaceName" json:"OutbundedAtPlaceName,omitempty"`
	TotalAmount               int64                       `protobuf:"varint,6,opt,name=TotalAmount" json:"TotalAmount,omitempty"`
	CompanyId                 int64                       `protobuf:"varint,7,opt,name=CompanyId" json:"CompanyId,omitempty"`
	Tel                       string                      `protobuf:"bytes,8,opt,name=Tel" json:"Tel,omitempty"`
}

func (m *ShopMessage) Reset()                    { *m = ShopMessage{} }
func (m *ShopMessage) String() string            { return proto.CompactTextString(m) }
func (*ShopMessage) ProtoMessage()               {}
func (*ShopMessage) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *ShopMessage) GetSaleOrderNo() string {
	if m != nil {
		return m.SaleOrderNo
	}
	return ""
}

func (m *ShopMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShopMessage) GetColorPatternRelationships() []*ColorPatternRelationship {
	if m != nil {
		return m.ColorPatternRelationships
	}
	return nil
}

func (m *ShopMessage) GetDeliveriedAtPlaceName() string {
	if m != nil {
		return m.DeliveriedAtPlaceName
	}
	return ""
}

func (m *ShopMessage) GetOutbundedAtPlaceName() string {
	if m != nil {
		return m.OutbundedAtPlaceName
	}
	return ""
}

func (m *ShopMessage) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *ShopMessage) GetCompanyId() int64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *ShopMessage) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

type ManagerAccount struct {
	CompanyId int64 `protobuf:"varint,1,opt,name=CompanyId" json:"CompanyId,omitempty"`
	OrgId     int64 `protobuf:"varint,2,opt,name=OrgId" json:"OrgId,omitempty"`
}

func (m *ManagerAccount) Reset()                    { *m = ManagerAccount{} }
func (m *ManagerAccount) String() string            { return proto.CompactTextString(m) }
func (*ManagerAccount) ProtoMessage()               {}
func (*ManagerAccount) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *ManagerAccount) GetCompanyId() int64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *ManagerAccount) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

// 当日营业额统计
type TurnoverStatistics struct {
	TotalOrders  int64 `protobuf:"varint,1,opt,name=TotalOrders" json:"TotalOrders,omitempty"`
	TotalAmount  int64 `protobuf:"varint,2,opt,name=TotalAmount" json:"TotalAmount,omitempty"`
	ActualAmount int64 `protobuf:"varint,3,opt,name=ActualAmount" json:"ActualAmount,omitempty"`
}

func (m *TurnoverStatistics) Reset()                    { *m = TurnoverStatistics{} }
func (m *TurnoverStatistics) String() string            { return proto.CompactTextString(m) }
func (*TurnoverStatistics) ProtoMessage()               {}
func (*TurnoverStatistics) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *TurnoverStatistics) GetTotalOrders() int64 {
	if m != nil {
		return m.TotalOrders
	}
	return 0
}

func (m *TurnoverStatistics) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *TurnoverStatistics) GetActualAmount() int64 {
	if m != nil {
		return m.ActualAmount
	}
	return 0
}

type GeneralMangerMessage struct {
	CompanyId          int64               `protobuf:"varint,1,opt,name=CompanyId" json:"CompanyId,omitempty"`
	UserId             int64               `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	TurnoverStatistics *TurnoverStatistics `protobuf:"bytes,3,opt,name=TurnoverStatistics" json:"TurnoverStatistics,omitempty"`
}

func (m *GeneralMangerMessage) Reset()                    { *m = GeneralMangerMessage{} }
func (m *GeneralMangerMessage) String() string            { return proto.CompactTextString(m) }
func (*GeneralMangerMessage) ProtoMessage()               {}
func (*GeneralMangerMessage) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *GeneralMangerMessage) GetCompanyId() int64 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *GeneralMangerMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GeneralMangerMessage) GetTurnoverStatistics() *TurnoverStatistics {
	if m != nil {
		return m.TurnoverStatistics
	}
	return nil
}

type GeneralMangerMessages struct {
	GeneralMangerMessages []*GeneralMangerMessage `protobuf:"bytes,1,rep,name=GeneralMangerMessages" json:"GeneralMangerMessages,omitempty"`
}

func (m *GeneralMangerMessages) Reset()                    { *m = GeneralMangerMessages{} }
func (m *GeneralMangerMessages) String() string            { return proto.CompactTextString(m) }
func (*GeneralMangerMessages) ProtoMessage()               {}
func (*GeneralMangerMessages) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *GeneralMangerMessages) GetGeneralMangerMessages() []*GeneralMangerMessage {
	if m != nil {
		return m.GeneralMangerMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*SaleOrder)(nil), "igrpc.SaleOrder")
	proto.RegisterType((*WarehouseManagerMessage)(nil), "igrpc.WarehouseManagerMessage")
	proto.RegisterType((*WarehouseManagers)(nil), "igrpc.WarehouseManagers")
	proto.RegisterType((*ShopMessage)(nil), "igrpc.ShopMessage")
	proto.RegisterType((*ManagerAccount)(nil), "igrpc.ManagerAccount")
	proto.RegisterType((*TurnoverStatistics)(nil), "igrpc.TurnoverStatistics")
	proto.RegisterType((*GeneralMangerMessage)(nil), "igrpc.GeneralMangerMessage")
	proto.RegisterType((*GeneralMangerMessages)(nil), "igrpc.GeneralMangerMessages")
}

func init() { proto.RegisterFile("sale.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x26, 0x90, 0x09, 0x14, 0x58, 0xa5, 0xb0, 0x05, 0x04, 0xd1, 0x9e, 0x72, 0xca,
	0x21, 0xf0, 0x03, 0x51, 0x2b, 0x21, 0x1f, 0xd2, 0x14, 0x27, 0xa8, 0x12, 0x12, 0x87, 0xad, 0x3d,
	0x4a, 0x8c, 0x36, 0xbb, 0xd6, 0xee, 0xba, 0x12, 0x12, 0xff, 0xc1, 0xdf, 0xf0, 0x21, 0x7c, 0x0d,
	0xea, 0xda, 0x75, 0x1c, 0xc7, 0xe6, 0xc8, 0xcd, 0xf3, 0xe6, 0xcd, 0xcc, 0x7b, 0x63, 0x8f, 0x01,
	0x0c, 0x17, 0x38, 0xcd, 0xb4, 0xb2, 0x8a, 0xf4, 0xd2, 0x8d, 0xce, 0xe2, 0xd7, 0x4f, 0x33, 0xad,
	0x92, 0x3c, 0xb6, 0x05, 0xca, 0x6e, 0x60, 0xb0, 0xe2, 0x02, 0x97, 0x3a, 0x41, 0x4d, 0xc6, 0x30,
	0xac, 0x82, 0x30, 0xa1, 0xde, 0xd8, 0x9b, 0x04, 0x51, 0x1d, 0x22, 0x13, 0x78, 0xb6, 0x0f, 0x2d,
	0xee, 0xc2, 0x84, 0xfa, 0x8e, 0xd5, 0x84, 0xd9, 0x6f, 0x0f, 0x5e, 0xdd, 0x70, 0x8d, 0x5b, 0x95,
	0x1b, 0x5c, 0x70, 0xc9, 0x37, 0xa8, 0x17, 0x68, 0x0c, 0xdf, 0x20, 0x21, 0x70, 0x72, 0xc5, 0x77,
	0xe8, 0x06, 0x0c, 0x22, 0xf7, 0x4c, 0x4e, 0xc1, 0xaf, 0x9a, 0xf9, 0x61, 0x42, 0xbe, 0xc1, 0xf9,
	0x85, 0x12, 0x4a, 0x5f, 0x73, 0x6b, 0x51, 0xcb, 0x08, 0x05, 0xb7, 0xa9, 0x92, 0x66, 0x9b, 0x66,
	0x86, 0x06, 0xe3, 0x60, 0x32, 0x9c, 0xbd, 0x9f, 0x3a, 0x4b, 0xd3, 0x2e, 0x5e, 0xd4, 0xdd, 0xe1,
	0xc0, 0xea, 0x95, 0xa2, 0x27, 0x4e, 0x49, 0x1d, 0x62, 0x0a, 0x5e, 0x34, 0xf5, 0x1b, 0xf2, 0x15,
	0x68, 0x87, 0x29, 0x43, 0x3d, 0x27, 0xea, 0x5d, 0x29, 0xaa, 0x83, 0x16, 0x75, 0xd6, 0xb3, 0x3f,
	0x3e, 0x0c, 0x57, 0x5b, 0x95, 0x3d, 0x6c, 0xa9, 0x21, 0xd1, 0x3b, 0x92, 0xf8, 0xbf, 0x77, 0xf6,
	0x11, 0xce, 0x2e, 0x51, 0xa4, 0x77, 0xa8, 0x53, 0x4c, 0xe6, 0xf6, 0x5a, 0xf0, 0x18, 0xdd, 0x7b,
	0x2c, 0xb6, 0xd7, 0x9e, 0x24, 0x33, 0x18, 0x2d, 0x73, 0x7b, 0x9b, 0xcb, 0xe4, 0xb0, 0xa8, 0xe7,
	0x8a, 0x5a, 0x73, 0xf7, 0xd6, 0xd7, 0xca, 0x72, 0x31, 0xdf, 0xa9, 0x5c, 0x5a, 0xda, 0x2f, 0x3e,
	0xc4, 0x1a, 0x44, 0xde, 0xc2, 0xe0, 0x42, 0xed, 0x32, 0x2e, 0x7f, 0x84, 0x09, 0x7d, 0xe4, 0xf2,
	0x7b, 0x80, 0x3c, 0x87, 0x60, 0x8d, 0x82, 0x3e, 0x76, 0x23, 0xee, 0x1f, 0xd9, 0x25, 0x9c, 0x96,
	0xfb, 0x9e, 0xc7, 0xf1, 0x71, 0x07, 0xaf, 0xd9, 0x61, 0x04, 0xbd, 0xa5, 0xde, 0x54, 0xdb, 0x2d,
	0x02, 0xf6, 0x13, 0xc8, 0x3a, 0xd7, 0x52, 0xdd, 0xa1, 0x5e, 0x59, 0x6e, 0x53, 0x63, 0xd3, 0xd8,
	0x54, 0x6a, 0xdd, 0x6b, 0x31, 0x0f, 0x67, 0x53, 0x83, 0x9a, 0x7e, 0xfc, 0x63, 0x3f, 0x0c, 0x9e,
	0xcc, 0x63, 0x9b, 0x57, 0x94, 0xc0, 0x51, 0x0e, 0x30, 0xf6, 0xcb, 0x83, 0xd1, 0x27, 0x94, 0xa8,
	0xb9, 0x58, 0x70, 0x59, 0xbb, 0xa7, 0x7f, 0x5b, 0x79, 0x09, 0xfd, 0x2f, 0xc6, 0x1d, 0x74, 0x31,
	0xb7, 0x8c, 0x48, 0xd8, 0x66, 0xc6, 0x0d, 0x1e, 0xce, 0xce, 0xcb, 0xcf, 0xe4, 0x98, 0x10, 0xb5,
	0x14, 0xb1, 0xef, 0x70, 0xd6, 0x26, 0xcc, 0x90, 0xcf, 0x1d, 0x89, 0xf2, 0x58, 0xde, 0x94, 0x63,
	0xda, 0x38, 0x51, 0x7b, 0xe5, 0x6d, 0xdf, 0xfd, 0xb8, 0x3e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0x5a, 0xc2, 0x4b, 0xdc, 0x04, 0x00, 0x00,
}
